name: Run Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.19','1.20']
    
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: rawdb
      
    name: Go ${{ matrix.go }} Tests
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests in test directory
      run: cd src/tests && go test -v
